/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package MasterThesis;

import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
    @Test public void testAppHasAGreeting() {
        MainApp classUnderTest = new MainApp();
       // assertNotNull("app should have a greeting", classUnderTest.getGreeting());

    }
}
