/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package MasterThesis;
//TODO Encje naglowkow plikow wynikowych
//TODO Encje artosci wyliczen do plikow wynikowych
//TODO Wykluczenie poskich znaków powdują znaki nowych lini readerze
//Jednoliczta obsluga błędow
// odczytu pliku
// bledow w pliku

//GŁÓWY PROG
/*
 poranie praramretrow
 jezeli potrzeba w zależności od paramerow to czytaj wszystkie dane z plikow
 zbuduj listy wszystkicj plikow
 zbuduj mape sieci
 wykoneja przejści i obliczenia

 w zależności od parametrow zapisz obliczenia

* */

import MasterThesis.arc.ArcFactory;
import MasterThesis.base.parameters.AppParameters;
import MasterThesis.base.parameters.AppParametersService;
import MasterThesis.bfs.ElectricalNetwork;
import MasterThesis.bfs.FileDataReader;
import MasterThesis.line_type.LineTypeFactory;
import MasterThesis.node.NodeFactory;
import MasterThesis.transformer_type.TransformerTypeFactory;

import java.io.*;
import java.util.Scanner;
import java.util.function.Consumer;

public class MainApp {

    public static void main(String[] args) throws FileNotFoundException {

        AppParametersService paramsService =  AppParametersService.getInstance();
        ElectricalNetwork elNet = ElectricalNetwork.getInstance();
        elNet.initList();


        FileDataReader.netFileRead(paramsService.getNodeFileFullPath(),
                    s ->  elNet.nodeList.add(NodeFactory.prepareFromString(s)));

        FileDataReader.netFileRead(paramsService.getTransformerTypeFullFileName(),
                    s ->  elNet.transformerTypeList.add(TransformerTypeFactory.prepareFromString(s)));

        FileDataReader.netFileRead(paramsService.getLineTypeFullFileName(),
                s ->  elNet.lineTypeList.add(LineTypeFactory.prepareFromString(s)));

        FileDataReader.netFileRead(paramsService.getArcFullFileName(),
                s ->  elNet.arcEntityList.add(ArcFactory.prepareFromString(s)));
        //-------------------
        System.out.println("ILOSC WEZLOW : "+elNet.nodeList.size());
        System.out.println("ILOSC Lukow : "+elNet.arcEntityList.size());
        System.out.println("ILOSC Typow Trafo : "+elNet.transformerTypeList.size());
        System.out.println("ILOSC tyow lini : "+elNet.lineTypeList.size());



    }
}
